server:
    port: 8080
    servlet:
        context-path: /api

spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1
        username: sa
        password:
    h2:
        console:
            enabled: true
            path: /h2
        jpa:
            database-platform: org.hibernate.dialect.H2Dialect
            show-sql: true
            properties:
                hibernate:
                    format_sql: true
            hibernate:
                ddl-auto: none
    liquibase:
        change-log: classpath:/liquibase/liquibase.xml
    boot:
        admin:
            client:
                instance:
                    name: book-api
                    management-url: http://localhost:8080/actuator
                    health-url: http://localhost:8080/actuator/health
                    service-url: http://localhost:8080/swagger-ui.html